version: '2.13.0'

services:

  kali:
    build: ./kali
    container_name: kali
    hostname: kali
    tty: true
    networks:
      vulhubnet:
        ipv4_address: 172.20.0.100
    volumes: 
      - ./code-python:/code-python
      - ./code-golang:/code-golang


networks:
  vulhubnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.1/24
          gateway: 172.20.0.1

